from odoo import models, fields, api

class PurchaseOrder(models.Model):
    _inherit = 'purchase.order'

    # We add readonly=True and copy=False so that it isn't copied if the PO is duplicated manually
    is_auto_generated = fields.Boolean(
        string='Automatically Generated', 
        default=False, 
        readonly=True,
        copy=False,
        help='Indicates if this purchase order was generated by the system based on projected demand.'
    )

    def button_confirm(self):
        """
        We click the “Confirm” button to update the “Last Purchase Cost”
        for each product included in the order.
        """
        # We run Odoo's native behavior first
        res = super(PurchaseOrder, self).button_confirm()
        
        # We iterate over the order lines to update the products
        for order in self:
            for line in order.order_line:
                if line.product_id and line.price_unit > 0:
                    line.product_id.last_purchase_cost = line.price_unit
                    
        return res