from odoo import models, fields

class PurchaseRequisition(models.Model):
    _inherit = 'purchase.requisition'

    is_auto_generated = fields.Boolean(
        string='Automatically Generated', 
        default=False, 
        readonly=True,
        copy=False,
        help='Indicates if this tender was generated by the system.'
    )